[package]
name = "roblox-username-tester"
version = "0.1.0"
edition = "2018"
author = ["Pavlos Efstathiou"]

[dependencies]
tokio = { version = "0.2.21", features = ["macros"] }
hyper = "0.13"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
hyper-tls = "0.4"